name: amazon_rainforest_model
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - plotly
  - dash
  - jupyterlab
  - notebook
  - ipykernel
  - matplotlib
  - pandas
  - scipy
